use crate::{random_gen, utils::*};
use lazy_static::*;
use rand::distributions::Alphanumeric;
use rand::{thread_rng, Rng};
use std::borrow::Cow;
use std::collections::BTreeSet;

pub struct Foo {
    value: String,
    valid: bool,
}

fn new_foo(len: usize) -> Foo {
    Foo {
        value: random_word(len),
        valid: random_gen!(bool),
    }
}

fn use_value(a: &str) -> String {
    a.to_owned()
}

lazy_static! {
    static ref n: Foo = new_foo(1000);
}

pub fn touch_n() -> bool {
    // touch the static variable generated by the lazy_static
    n.valid
}

fn new_words(num: usize, len: usize) -> Vec<String> {
    let mut _words: Vec<String> = (0..num)
        .map(|_| {
            thread_rng()
                .sample_iter(&Alphanumeric)
                .take(len)
                .map(char::from)
                .collect()
        })
        .collect();
    let tmp = _words.get(0).unwrap().clone();
    _words.push(tmp);
    _words
}

lazy_static! {
    static ref words: Vec<String> = new_words(1000, 2);
}

pub fn _1f() {
    let value = if n.valid {
        n.value.to_ascii_lowercase().to_string()
    } else {
        n.value.to_string()
    };
    use_value(&value);
}

pub fn _1o() {
    let value = if n.valid {
        Cow::Owned(n.value.to_ascii_lowercase())
    } else {
        Cow::Borrowed(&n.value)
    };
    use_value(&value);
}

pub fn _2f() {
    let mut idents: BTreeSet<String> = BTreeSet::new();
    for ident in words.iter() {
        if idents.contains(ident) {
            use_value(&ident);
            break;
        }
        idents.insert(ident.clone());
    }
}

pub fn _2o() {
    let mut idents: BTreeSet<&str> = BTreeSet::new();
    for ident in words.iter() {
        if idents.contains(ident.as_str()) {
            use_value(&ident);
            break;
        }
        idents.insert(ident);
    }
}
